
ifeq ($(findstring YES,$(CONFIG_INCLUDE_VIRTUAL_BASS)),YES)
    _INCLUDE_COMMON_DSP :=YES
    _INCLUDE_DSP_MANAGMENT :=YES
	INCLUDE_THIS_COMPONENT := YES   # must be here !!
endif

#INCLUDE_DIR

#DEFINES =

#CFLAGS =

#ASMFLAGS =




SRC = virtual_bass.c

ifeq ($(findstring AS_SPEED_CRITICAL,$(CONFIG_INCLUDE_VIRTUAL_BASS)),AS_SPEED_CRITICAL)
    SPEED_CRITICAL_FILES += virtual_bass.c
    _COMMON_DSP_IS_SPEED_CRITICAL := YES
endif

VPATH = src


include $(COMMON_CC)
